### ISSUE TITLE
error extract manifest

### ISSUE THREAD

**Issue by mattia-b89** [boxingsquirrel/idevicerestore#3]
i noticed a little error: program can't extract manifest file.

this because there is a little typo in code: manifesto instead manifest

**Comment by boxingsquirrel** [comment]
That is to support older firmwares that don't require SHSH blobs and have a BuildManifesto.plist instead of a BuildManifest.plist. It will spit out an error but move on to the latter file, which should be present.

**Comment by mattia-b89** [comment]
ok, perfect

so, i suggest (but because program works this fix isn't needed...) an if case (automatic method) or ask to the user to enter iOS version (manual method)

**Comment by boxingsquirrel** [comment]
That's what it does, it just let's you know for debugging purposes that the file isn't present...

**Comment by mattia-b89** [comment]
ok, understand
