### ISSUE TITLE
usbmuxd_get_device_list: error opening socket!

### ISSUE THREAD

**Issue by Lars0160** [boxingsquirrel/idevicerestore#4]
1. idevicerestore -u 05ac:1227 ./iPhone3,1_4.0.2_8A400_Restore.ipsw | fb
2. opening device 05ac:1227...
3. Setting to configuration 1
4. Setting to interface 0:0
5. usbmuxd_get_device_list: error opening socket!
6. usbmuxd_get_device_list: error opening socket!
7. ERROR: Unable to discover device mode. Please make sure a device is attached

Waht's wrong?

**Comment by boxingsquirrel** [comment]
05ac:1227 isn't a valid UUID, which is 40 digits. The UUID can be found in the Settings app on the device (General->About).
